### PR TITLE
fix(nfts page): fix nfts page data display, add nft card preloader

### LINKED ISSUE #48: Layout glitches on NFT treasury page
Layout is jumping around on this NFT display page even after images visually appear to have loaded (but in console appear to still be loading) 

https://app.astrodao.com/dao/nearchan.sputnik-dao.near/treasury/nfts 

ezgif-3-6f06387fa362

### PR DESCRIPTION
**Pull request by VERZUOL1**

### CODE REVIEW

File: pages/dao/[dao]/treasury/nfts/index.ts [hunk 1]
```diff
@@ -16,9 +16,8 @@ export const getServerSideProps: GetServerSideProps<NFTsPageProps> = async ({
 
   const account = CookieService.get<string | undefined>(ACCOUNT_COOKIE);
 
-  const [daoContext, nfts] = await Promise.all([
+  const [daoContext] = await Promise.all([
```
Comment (AlexeyPonomarenko) [inline pages/dao/[dao]/treasury/nfts/index.ts:19]: Do we still need promise all here?

File: features/nft/ntf-card/ntf-card.module.scss [hunk 2]
```diff
@@ -1,6 +1,82 @@
...
+.preloaderIcon div {
+  animation: preloader 1.2s cubic-bezier(0, 0.5, 0.5, 1) infinite;
+  background: var(--color-brand-purple-light);
+  display: inline-block;
+  left: 8px;
+  position: absolute;
+  width: 16px;
+}
+
+.preloaderIcon div:nth-child(1) {
```
Comment (AlexeyPonomarenko) [inline features/nft/ntf-card/ntf-card.module.scss:58]: I would suggest to avoid usage of tags and nth-child if we can make the same using classes.

**Review by AlexeyPonomarenko — APPROVED** [review]
