### PR TITLE
fix(badge color): make consistant group color

### LINKED ISSUE #940: Chips that show group membership do not have consistent colors
**Describe the bug**
Chips are not colored per group, rather they are colored based on how many chips each person has.

**Expected behavior**
In the screenshot, all Council members group chips should be the #DAF8FF. Instead neartesting.near Council chip is #DAE9FF.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by VERZUOL1**

### CODE REVIEW

File: components/Badge/Badge.tsx [hunk 1]
```diff
@@ -30,6 +30,29 @@ interface BadgeProps extends React.HTMLAttributes<HTMLDivElement> {
   variant?: Variant;
 }
 
+export function getBadgeVariant(name: string): Variant {
```
Comment (AlexeyPonomarenko) [inline components/Badge/Badge.tsx:33]: The helper method is not being used in component, so placing it here looks a bit strange. Maybe, we can place it in proper file near by?

Comment (VERZUOL1) [reply components/Badge/Badge.tsx:33]: It is a method that should be used together with component, so I would like to keep it in the same file

**Review by dmytro-almighty — APPROVED** [review]
