### PR TITLE
fix(feed): show loader when we toggle filters to avoid showing old co…

### LINKED ISSUE #160: Failed proposal showing under "Active" proposals
image

Expected: "Failed" proposal appears under "All" and "Failed" fliters but not "Active" or "Passed" filters.

### PR DESCRIPTION
**Pull request by VERZUOL1**
…ntent

### CODE REVIEW

**Review by dmytro-almighty — APPROVED** [review]

File: components/loader/Loader.tsx [hunk 1]
```diff
@@ -84,13 +85,15 @@ const PRELOADER = (
 
 interface LoaderProps {
   title?: string;
+  className?: string;
 }
 
 export const Loader: FC<LoaderProps> = ({
   title = 'Receiving data from the contract',
+  className = '',
```
Comment (AlexeyPonomarenko) [inline components/loader/Loader.tsx:93]: There is no need to provide default value. Undefined will work great too)

File: astro_2.0/features/Feed/Feed.tsx [hunk 2]
```diff
@@ -201,34 +208,40 @@ export const Feed = ({
...
-                  dao={proposal.dao}
-                  proposal={proposal}
-                  showFlag={showFlag}
-                  tokens={daoTokens || tokens}
-                />
-              </div>
+        {loading ? (
+          <Loader className={styles.loader} />
+        ) : (
+          <>
```
Comment (AlexeyPonomarenko) [inline astro_2.0/features/Feed/Feed.tsx:214]: I don't think there is a need in wrapping it into <></>

**Review by AlexeyPonomarenko — APPROVED** [review]
