### PR TITLE
fix(voting policy proposal): fix value format for change viting polic…

### LINKED ISSUE #381: Consensus policy change displaying a different % than I input in the proposal
https://app.astrodao.com/dao/curators.sputnik-dao.near/proposals/curators.sputnik-dao.near-73

image

on chain threshold is indeed 39% https://explorer.mainnet.near.org/transactions/7LiNM3LbYbB9XMq9mvR5uebxv7MRZQ64ZSuYfiFKmQSH

image

### PR DESCRIPTION
**Pull request by VERZUOL1**
…y proposals

### CODE REVIEW

File: features/vote-policy/helpers.ts [hunk 1]
```diff
@@ -137,7 +139,9 @@ export const getInitialData = (
       voteBy: defaulPolicy.weightKind === 'RoleWeight' ? 'Person' : 'Token',
       amount:
         defaulPolicy?.ratio && defaulPolicy.ratio.length
-          ? (defaulPolicy.ratio[0] / defaulPolicy.ratio[1]) * 100
+          ? Number(
+              ((defaulPolicy.ratio[0] / defaulPolicy.ratio[1]) * 100).toFixed(2)
```
Comment (dmytro-almighty) [inline features/vote-policy/helpers.ts]: please extract this to separate function

**Review by AlexeyPonomarenko — DISMISSED** [review]

**Review by dmytro-almighty — CHANGES_REQUESTED** [review]

**Review by dmytro-almighty — APPROVED** [review]
